# Generated by Django 5.2.5 on 2025-09-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
