# Generated by Django 5.2.5 on 2025-09-04 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
