# Generated by Django 5.2.5 on 2025-10-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_secret',
        ),
    ]
